### ISSUE TITLE
Could not get list of accounts.

### ISSUE THREAD

**Issue by Spottycat** [mirkowein/moneymoney-whitebox#1]
Hallo, 

leider ist es aktuell nicht möglich eine Umsatzabfrage durchzuführen.
Ich bekomme lediglich "Could not get list of accounts." im Logfile.

Received gibt HTML aus, welches mich namentlich begrüsst und auch den Depotstand beinhaltet. Daher hat der Login wohl korrekt funktioniert. 

Vermutlich hat sich das HTML der Seite im letzten Jahr verändert.

<img width="674" alt="screen shot 2018-09-20 at 11 12 19" src="https://user-images.githubusercontent.com/1735055/45808431-1532d700-bcc6-11e8-9b69-a34432de2478.png">

**Comment by mirkowein** [comment]
Hallo, 

ich habe es gefixt, allerdings muss es erst noch von MoneyMoney signiert werden.
Sobald das passiert ist, sollte es wieder laufen. Die Neue Version wird dann dort eingestellt werden:
https://moneymoney-app.com/extensions/

Gerne Feedback dann.

Viele Grüße
