### ISSUE TITLE
Konto in MoneyMoney anlegen funktioniert nicht

### ISSUE THREAD

**Issue by GabZach** [mirkowein/moneymoney-whitebox#2]
Hallo Mirko,

sorry , dass ich hierüber versuche, dich zu kontaktieren - wusste nicht, wie ich sonst dir eine Frage schicken kann.

Ich habe deine Extension (vielen Dank!) in den Extension-Folder von MoneyMoney kopiert, MM neu gestartet (die Extension wird auch korrekt in Preferences/Extensions angezeigt), aber leider kann ich immer noch kein Whitebox-Konto in MM anlegen.
Ich habe sowohl meine normalen Login-Credentials probiert (die ich auch zum Einloggen auf der Whitebox-Webseite verwende), als auch mit meiner Kundennummer.

Mache ich etwas falsch?

Vielen Dank im Voraus.

**Comment by mirkowein** [comment]
Hallo Gabriel,

aktuell habe ich leider keinen Zugriff auf einen Mac. Frühestens nächste Woche. Vielleicht kannst Du mir in der Zwischenzeit Infos zukommen lassen, was genau der Fehler ist. Meldungen im Fenster, Screenshots etc. 

Viele Grüße 
Mirko

Von einem mobilen Gerät versendet. Evtl. Telegrammstil bitte ich zu entschuldigen

**Comment by GabZach** [comment]
Danke für die Antwort - ich glaube ich habe es herausgefunden: man darf keinen "normalen" Account anlegen, sondern muss unten "Other" auswählen ...

Herzliche Grüße, Gabriel

**Comment by mirkowein** [comment]
Hallo Gabriel,

klappt jetzt alles? Oder gibt es noch Probleme?

Viele Grüße 
Mirko

Von einem mobilen Gerät versendet. Evtl. Telegrammstil bitte ich zu entschuldigen

> Am 03.10.2018 um 13:17 schrieb GabZach <notifications@github.com>:
> 
> Danke für die Antwort - ich glaube ich habe es herausgefunden: man darf keinen "normalen" Account anlegen, sondern muss unten "Other" auswählen ...
> 
> Herzliche Grüße, Gabriel
> 
> 
>

**Comment by GabZach** [comment]
Ja, danke, soweit ich sehen kann, klappt jetzt alles.

Herzliche Grüße, Gabriel

**Comment by mirkowein** [comment]
Schlechte Beschreibung, man muss other als Accounttyp wählen.
