### ISSUE TITLE
Diskrepanz zwischen den Angaben in MoneyMoney und denen auf der Whitebox-Webseite

### ISSUE THREAD

**Issue by GabZach** [mirkowein/moneymoney-whitebox#4]
Die Beträge der angezeigten Konten "Konto" und "Depot" weichen von denen In der Whitebox-Webseite angezeigten ab.

Der Support schreibt dazu folgendes als Grund:
Was die Abweichung zwischen dem Bestand Ihres "Depot Vermehrung" in MoneyMoney und dem Depotbestand in Ihrem Whitbox-Account unter "Portfolio" - "Depotbestand" angeht, hilft ein Blick in den Code der von Ihnen genutzten Erweiterung. Diese liest die Daten aus Ihrem Account aus dem Bereich "Protokoll" - "Depotumsätze" aus, der Depotbestand dort gibt den exakten Bestand des Depots mit 15min Zeitverzögerung an. 
Im von Ihnen genannten Bereich "Portfolio" - "Depotbestand" ist (etwas missverständlich) nicht der reine Depotbestand angegeben, sondern der Gesamtwert dieses Ziels, also tatsächlich die Gesamtsumme aus Depot und Cashkonto. Dies erkennen Sie an der Auflistung in der dortigen Tabelle: Die letzte Zeile gibt den aktuellen Bestand Ihres Cash-Kontos wieder, der in hier dargestellten "Depotbestand" mit einfließt. Dieser sollte also der Summe aus "Konto Vermehrung" und "Depot Vermehrung" in MoneyMoney entsprechen.

Vielleicht kann man das reparieren.

**Comment by mirkowein** [comment]
Hallo, so ganz verstehe ich das Problem nicht.
Für jedes `Ziel` werden 2 Konten angelegt. 
- `Konto <ziel>`zeigt den Cash an 
- `Depot <ziel>` zeigt den Wert des Portfolios an

Zusammen macht das den Wert des `<ziel>`s aus.
Am besten man nutzt "Kontostand in Saldenleiste anzeigen" als Kontogruppe in MoneyMoney. (In der Read.me unter Tipp)

![](https://raw.githubusercontent.com/mirkowein/moneymoney-whitebox/master/Screenshots/Kontogruppe.png)

Hilft das weiter, oder Thema verfehlt?

**Comment by mirkowein** [comment]
Ich habe Version 1.5 Online gestellt. Damit hat mal alle Wahlfreiheit. Aber weiterhin wichtig ist, als Kontengruppe zu gruppieren.

**Comment by GabZach** [comment]
Super - vielen Dank.

**Comment by GabZach** [comment]
Hi Mirko,

der Zugang zum Whitebox Account scheint nicht mehr zu funktionieren.

Ich habe gerade ein paar verwirrende Meldungen von MoneyMoney bekommen.

Zunächst kam diese Meldung:


Dann habe ich akzeptieren geklickt, und direkt danach kam diese Meldung:


Das verwunderliche war, dass der SHA1 Fingerprint ein *anderer* als in der ersten Meldung war!
Was bedeutet das?  Warum gibt der Server für dasselbe Konto zwei verschiedene SHA1 fingerprints aus?
Es kann ja sicherlich nur einer stimmen.

Nach dem Akzeptieren dieser Meldung hat MM normal gestartet.
Allerdings war neben dem Whitebox-Konto diese Fehlermeldung zu sehen:



Bedeutet das, dass der Server einfach down war, und die Meldung bzgl der Fingerprints gar nichts zu sagen hat?
Er ist allerdings auch 4 Stunden später noch nicht zugänglich.


Hast Du eine Idee, was das Problem ist?


Verwirrte Herzliche Grüße, Ihr G. Zachmann

**Comment by mirkowein** [comment]
Hallo Gabriel,

aktuell scheint Whitebox noch zu 'basteln'. Ich kriege manchmal Timeouts über einen Proxy. 
Aber später geht es dann wieder. Deine Fehlermeldung kann ich nicht sehen.
Mit den SHA1 Fingerprints denke ich, das liegt daran, dass das Skript 2 Subdomains anspricht:
www.whitebox.eu
inside.whitebox.eu

Vielleicht wartest Du bist sie es stabil haben. Ich selbst kann aktuell abrufen mit Version 1.06 des Skripts.

Viele Grüße
Mirko

**Comment by GabZach** [comment]
Danke - habe gerade die neue Erosion heruntergeladen, jetzt geht es.

Herzliche Grüße, Gabriel

**Comment by GabZach** [comment]
Hallo Mirko,

seit ein paar Tagen liefert MoneyMoney wieder die Fehlermeldung, dass die Verbindung zum Whitebox-Server fehlgeschlagen ist.
Funktioniert es bei dir?

Herzliche Grüße, Gabriel

**Comment by schlueed** [comment]
Hallo,
ich nutze auch das Whitebox-Plugin und auch bei mir ist leider keine Aktualisierung mehr möglich. Letztmalig hat es am 16.06. funktioniert, danach nur noch der Hinweis in MoneyMoney: "Der Server Ihrer Bank meldet einen internen Fehler. Bitte versuchen Sie es später noch einmal."
Viele Grüße
Edgar
