### ISSUE TITLE
Whitebox Kundenbereich URL geändert

### ISSUE THREAD

**Issue by calcosta** [mirkowein/moneymoney-whitebox#5]
Es scheint so, als hätte Whitebox mal wieder die Urls geändert.
Auf den ersten Blick nur eine Umstellung des gesamten Kundenbereichs auf die Subdomain inside.whitebox.eu.

Die Pfade `/login` oder auch `/goals/[ZIELNAME]/statements` scheinen gleichgeblieben zu sein.

**Comment by mirkowein** [comment]
Ich bin dran, danke fürs Melden.

**Comment by mirkowein** [comment]
Fix ist online

**Comment by calcosta** [comment]
Super, vielen Dank!
