### ISSUE TITLE
Doppelter Wert von Ziel in Seitenleiste

### ISSUE THREAD

**Issue by AndiH** [mirkowein/moneymoney-whitebox#6]
Ich habe gerade (seit sehr langer Zeit) die Erweiterung auf den aktuellen Stand gebracht (btw, danke für das Plugin!).

Als (für mich) neues Feature gibt es jetzt _faux_ Konten, »Performance ZIEL N« und »Portfolio ZIEL N« in der Seitenleiste. Eine tolle Idee und übersichtliche Darstellung!

Allerdings taucht nun dadurch jedes Ziel doppelt in der Berechnung der Gesamtsumme aller Konten auf. Gibt es eine Möglichkeit, das zu verhindern?

Evtl. ist diese Anfrage auch ein Feature-Request an MoneyMoney selbst; dann würde ich's dorthin schicken.

**Comment by mirkowein** [comment]
Hi Andreas,

ich verstehe Deinen Ansatz, aber ich habe es versucht in der Readme zu erklären: 

> Es macht Sinn als Kontogruppe zu gruppieren. Also KONTO und DEPOT hat in der Summe den Vermögensstand. Oder KONTO und PORTFOLIO. **Es macht keinen Sinn DEPOT und PORTFOLIO zu haben.** Sie sind 2 Darstellungen des selben Vermögens. Die Summe wäre dann doppelt in Ihren Übersichten.
>
>Kurz:
>
>   KONTO + DEPOT oder
>     KONTO + PORTFOLIO
>     PERFORMANCE optional dazu.

Ich selbst habe Portfilio nur auf Nachfrage implementiert, ich selbst beachte es nicht, weil ich gar nicht wissen muss welche Aktien enthalten sind, mich interessiert nur der Wert des Depots. 

Es gibt aber eine Umgehungs-Möglichkeit: Die Kontogruppen 

Bei mir habe ich verschachtelte Gruppen:

A Gruppe Vermögen
A1 Gruppe Alle Konten
A1.1 Girokonto 1
A1.2 Festgelt 2
A1.3 Paypal
A2 Gruppe Whitebox
A2.1. Gruppe Ziel N
A2.1.1 Konto Ziel N
A2.1.2 Depot Ziel N
A2.1.3 Performance Ziel N
A2.2. Gruppe Ziel M
A2.2.1 Konto Ziel M
A2.2.2. Depot Ziel M
A2.2.3 Performance Ziel M
B Gruppe Doppelt
B1 Portfolio Ziel N
B2 Portfolio Ziel M

Dann hast Du unter A Dein gesamtes Vermögen. Du hast Deine Bankkonten als Summe, Du hast Whitebox als Summe, Du hast die Ziele jeweils als Summe.
Und B musst Du ignorieren. Oder Du verzichtest auf PORTFOLIO oder DEPOT, je nach Wunsch. (wie in der Readme angedeutet). Einfach löschen.

Ich hatte mit _moneymoney_ darüber geschrieben, aktuell gibt es keine Möglichkeit das aus der Gesamtmenge automatisch raus zu rechnen. Aber ich finde das ist mit den Kontogruppen ja trotzdem zu handhaben, und Herr Haller hat mit der PSD II wahrlich genug Arbeit zur Zeit. ;)

Hilft Dir das weiter?

**Comment by AndiH** [comment]
Danke für die ausführliche Antwort! (Und sorry für meine Verspätete…)

Ich sehe, dass _Depot_ und _Portfolio_ ähnliche Ansichten der gleichen Daten sind. Aber ich find es – zumindest jetzt auf den ersten Blick – sehr interessant: Einmal eine absolute Sicht (_Portfolio_) und einmal eine inkrementelle/relative Sicht (_Depot_).

Hinzufügen von hierarchischen Gruppen wäre tatsächlich eine Lösung. Im Moment gruppiere ich allerdings nach Anbieter – und das gefällt mir auch.

Ich stelle mal einen Feature-Request an den MoneyMoney-Entwickler. Vielleicht hat er ja Lust, neben des ganzen PSD2-Quatsches etwas _sinnvolles_ zu entwicklen ;).
