### ISSUE TITLE
Fehler "unbekannt" in Whitebox Abfrage

### ISSUE THREAD

**Issue by jeha314** [mirkowein/moneymoney-whitebox#8]
Hallo Mirko,

erstmal besten Dank für Deine Mühe und Zeit, die Du in die Entwicklung der Extension gesteckt hast.
Seit ein paar Tagen bekomme ich in der Portfolio Abfrage keine Anzeige der jeweiligen Wertpapiere mehr,
sondern nur noch die Anzeige "unbekannt".
Ist das bei dir /anderen ähnlich, oder habe ich dieses Problem exklusiv?
Danke und Viele Grüsse, Jens

**Comment by schlueed** [comment]
Hallo,
kann ich als Anwender ebenfalls bestätigen. Bei mir erscheint auch (Unbekannt) unter Portfolio. Abfrage läuft aber ansonsten ohne erkennbare Probleme.
VG Edgar

**Comment by mirkowein** [comment]
Hi zusammen,

ja Whitebox hat wieder etwas geändert. Ich hatte das Sonntag gefixt. Herr Haller hat mittlerweile das Plugin signiert. Ladet es dort herunter und gebt bitte Bescheid, ob es funktioniert. 

Viele Grüße Mirko

**Comment by schlueed** [comment]
Hallo,
funktioniert wieder. Besten Dank für die schnelle Korrektur.
VG Edgar

**Comment by mirkowein** [comment]
Super, danke

Gefixt in 1.08

**Comment by jeha314** [comment]
Hallo zusammen,

funktioniert wieder - super vielen Dank!
@Mirko: funktioniert Dein PP Donation Link noch?
Viele Grüsse, Jens

**Comment by mirko** [comment]
> Hallo zusammen,
> 
> funktioniert wieder - super vielen Dank!
> @mirko: funktioniert Dein PP Donation Link noch?
> Viele Grüsse, Jens

Nur weil ich grad eine notification bekam:
 - /ich/ bin @mirko und habe nix mit dem projekt zu tun
 - du meintest bestimmt @mirkowein 
 - dieser kommentar, damit @mirkowein - an welchen dein (@jeha314) kommentar vermutlich gerichtet war - auch notifiziert wird

**Comment by jeha314** [comment]
Besten Dank, so ist es .
